name: Create Daily Scrum Template Every Day

on:
  schedule:
    # 매일 오전 9시(KST)에 실행 (UTC 자정)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  create-md-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy and Rename Files
      run: |
        DATE=$(date +'%y-%m-%d')
        mkdir -p ${DATE}
        cp template.md ${DATE}/hardy.md
        cp template.md ${DATE}/mae.md
        cp template.md ${DATE}/sean.md
        cp template.md ${DATE}/tony.md
        cp template.md ${DATE}/aiden.md
        cp template.md ${DATE}/luna.md
        
    - name: Commit and Push
      run: |
        DATE=$(date +'%y-%m-%d')
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add ${DATE} daily scrum template files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    name: Create Daily Scrum Template Every Day

on:
  workflow_dispatch:

jobs:
  create-md-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy and Rename Files
      run: |
        DATE=$(date +'%y-%m-%d')
        mkdir -p ${DATE}
        cp template.md ${DATE}/hardy.md
        cp template.md ${DATE}/mae.md
        cp template.md ${DATE}/sean.md
        cp template.md ${DATE}/tony.md
        cp template.md ${DATE}/aiden.md
        cp template.md ${DATE}/luna.md
        
    - name: Commit and Push
      run: |
        DATE=$(date +'%y-%m-%d')
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add ${DATE} daily scrum template files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Send Notification to Discord
      run: |
        DATE=$(date +'%y-%m-%d')
        DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_DAILY_WEBHOOK_URL }}
        MESSAGE="${DATE} - 일일 보고 양식이 생성되었습니다."
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"${MESSAGE}\"}" \
             $DISCORD_WEBHOOK_URL

